<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GemForge.Domain\GemForge.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MIConvexHull" Version="1.1.19.1019" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
